# Generated by Django 2.1 on 2018-09-08 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.TextField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Sunday')),
                ('cur_date', models.DateField()),
                ('calories', models.IntegerField(default=0)),
                ('carb', models.IntegerField(default=0)),
                ('protein', models.IntegerField(default=0)),
                ('fat', models.IntegerField(default=0)),
                ('weight', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.TextField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_num', models.IntegerField(default=0)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.NutritionMonth')),
            ],
        ),
        migrations.AddField(
            model_name='nutritionday',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.NutritionWeek'),
        ),
    ]
