# Generated by Django 2.1 on 2018-09-13 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0003_auto_20180913_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='N/A')),
                ('type', models.TextField(choices=[('Push', 'Push'), ('Pull', 'Pull'), ('Legs', 'Legs'), ('Cardio', 'Cardio')], default='Push')),
                ('reps', models.IntegerField(default=0)),
                ('sets', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='nutritionday',
            name='weekday',
            field=models.TextField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Sunday'),
        ),
        migrations.AddField(
            model_name='exerciseitem',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.NutritionDay'),
        ),
    ]
