# Generated by Django 2.1 on 2018-09-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0004_auto_20180913_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseitem',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nutritionday',
            name='calories',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nutritionday',
            name='carbs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nutritionday',
            name='fat',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nutritionday',
            name='protein',
            field=models.IntegerField(null=True),
        ),
    ]
