# Generated by Django 2.1 on 2018-11-09 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0005_auto_20180913_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseitem',
            name='name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='exerciseitem',
            name='type',
            field=models.CharField(choices=[('Push', 'Push'), ('Pull', 'Pull'), ('Legs', 'Legs'), ('Cardio', 'Cardio')], default='Push', max_length=100),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack'), ('Other', 'Other')], default='Snack', max_length=100),
        ),
        migrations.AlterField(
            model_name='nutritionday',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nutritionday',
            name='carbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nutritionday',
            name='day_slug',
            field=models.CharField(default='00-00-00', max_length=100),
        ),
        migrations.AlterField(
            model_name='nutritionday',
            name='fat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nutritionday',
            name='protein',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nutritionday',
            name='weekday',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Sunday', max_length=100),
        ),
        migrations.AlterField(
            model_name='nutritionday',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nutritionmonth',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=100),
        ),
        migrations.AlterField(
            model_name='nutritionmonth',
            name='month_slug',
            field=models.CharField(default='00-00', max_length=100),
        ),
    ]
