# Generated by Django 2.1.5 on 2019-01-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0006_auto_20181108_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseitem',
            name='day',
        ),
        migrations.AddField(
            model_name='exerciseitem',
            name='day',
            field=models.ManyToManyField(to='diet.NutritionDay'),
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='day',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='day',
            field=models.ManyToManyField(to='diet.NutritionDay'),
        ),
    ]
