# Generated by Django 2.1.5 on 2019-01-16 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0007_auto_20190115_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciseitem',
            old_name='day',
            new_name='days',
        ),
        migrations.RenameField(
            model_name='fooditem',
            old_name='day',
            new_name='days',
        ),
    ]
