# Generated by Django 2.1 on 2018-09-30 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diet', '0005_auto_20180913_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resturant', models.TextField(default='Unknown')),
                ('taste_rating', models.IntegerField(default=0)),
                ('health_rating', models.IntegerField(default=0)),
                ('calories', models.IntegerField(default=0)),
                ('carbs', models.IntegerField(default=0)),
                ('protein', models.IntegerField(default=0)),
                ('fat', models.IntegerField(default=0)),
                ('review', models.TextField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.NutritionDay')),
            ],
        ),
    ]
