# Generated by Django 2.1 on 2018-09-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180930_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='day_slug',
            field=models.CharField(default='00-00-00', max_length=8),
        ),
        migrations.AlterField(
            model_name='review',
            name='images',
            field=models.FileField(default=None, upload_to='media/<django.db.models.fields.CharField>/'),
        ),
    ]
