# Generated by Django 2.1 on 2018-09-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_review_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='resturant',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
