# Generated by Django 2.1 on 2018-09-30 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180930_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='day_slug',
        ),
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='review',
            name='images',
            field=models.FileField(default=None, null=True, upload_to='blog/'),
        ),
    ]
